language: scala
scala: 2.11.7
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_bd976e462827_key -iv $encrypted_bd976e462827_iv  -in
  ./dist/.dropbox_uploader.enc -out dropbox_uploader -d
- docker pull cheminotorg/dbtest:latest
- docker run -d -p 127.0.0.1:7474:7474 cheminotorg/dbtest
- docker ps -a
- sleep 10
script:
- chmod a+x ./docker/test/changepassword.sh
- ./docker/test/changepassword.sh
- sbt test
- sbt one-jar
- chmod a+x ./dist/upload.sh
- dist/upload.sh
env:
  global:
    secure: CZOG6ttBsvyjIyfmqR+cTOTtnSg5sXaSVMXpHQkV86b6/nd/LGPpZrTNt4dE44AppCkKNtwbL3M5Hchk6kjjGE4zH0X+G6EMAlg0dgC3cXd3R/51iuC0Zcxhb9aR3fy6uDv60is8WqH1u7RGY2Fr6eg4eq66Z4kl+vGqlOp9z48=
