language: scala

scala:
  2.11.7

sudo: required

services:
  - docker

before_install:
    - docker pull cheminotorg/dbtest:latest
    - docker run -d -p 127.0.0.1:7474:7474 cheminotorg/dbtest
    - docker ps -a

script:
  - ./docker/test/changepassword.sh
  - sbt test
